name: Publish

on:
  push:
    branches:
      - master
env:
  BACKEND_USER: ${{ secrets.BACKEND_USER }}
  BACKEND_PASSWORD: ${{ secrets.BACKEND_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.1.0
      - run: yarn
      - run: yarn test
      - run: yarn build
      - run: curl -v -X POST -H 'Content-Type:application/json' -u ${{ env.BACKEND_USER }}:${{ env.BACKEND_PASSWORD }} -d @"build/proposals.json" http://116.203.218.213:3000/proposal/sync
